[versions]
minsdk = "21"
targetsdk = "33"
java = "VERSION_17"
kotlinJvmTarget = "17"
shot = "0.0.4"

android-build-tools = "8.2.0"
androidx-activity-compose = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.12.0"
androidx-fragment-testing = "1.6.2"
androidx-recyclerview = "1.3.2"
androidx-test = "1.5.2"
androidx-test-core = "1.5.0"
androidx-test-junit-ktx = "1.1.5"
androidx-test-orchestrator = "1.4.2"
androidx-test-rules = "1.5.0"
asm = "3.3.1"
commons-io = "2.11.0"
compose = "1.5.4"
compose-compiler = "1.5.6"
espresso = "3.5.1"
dexopener = "2.0.5"
facebook-screenshot = "0.15.0"
flexmark-profile-pegdown = "0.64.8"
gson = "2.10"
json4s = "4.0.6"
junit = "4.13.2"
keyboardvisibilityevent = "2.0.0"
kodein = "4.1.0"
kotlin = "1.9.21"
kotlin-coroutines = "1.7.3"
kotlin-coroutines-test = "1.7.3"
material = "1.11.0"
mockito-android = "5.1.1"
mockito-kotlin = "5.0.0"
lifecycle = "2.6.2"
picasso = "2.5.2"
robolectric = "4.9.2"
scala-library = "2.13.11"
scala-parallel = "1.0.4"
scala-xml = "2.1.0"
scalamock = "5.2.0"
scalatest = "3.2.16"
scrimage = "4.0.37"
skyiko-ktlint = "0.29.0"
tinyzip = "1.0.0"
vanniktech-maven-publish = "0.25.3"

[libraries]
androidx-activity-compose = {module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose"}
androidx-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat"}
androidx-compose-material = {module = "androidx.compose.material:material", version.ref = "compose"}
androidx-compose-test = {module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose"}
androidx-compose-ui = {module = "androidx.compose.ui:ui", version.ref = "compose"}
androidx-compose-ui-tooling = {module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}
androidx-constraint-layout = {module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout"}
androidx-core = {module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-espresso-contrib = {module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso"}
androidx-espresso-core = {module = "androidx.test.espresso:espresso-core", version.ref = "espresso"}
androidx-espresso-intents = {module = "androidx.test.espresso:espresso-intents", version.ref = "espresso"}
androidx-fragment-testing = {module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment-testing"}
androidx-lifecycle-compiler = {module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle"}
androidx-lifecycle-runtime = {module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle"}
androidx-recyclerview = {module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview"}
androidx-test-core = {module = "androidx.test:core-ktx", version.ref = "androidx-test-core"}
androidx-test-junit-ext = {module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit-ktx"}
androidx-test-orchestrator = {module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator"}
androidx-test-rules = {module = "androidx.test:rules", version.ref = "androidx-test-rules"}
androidx-test-runner = {module = "androidx.test:runner", version.ref = "androidx-test"}
asm = {module = "asm:asm", version.ref = "asm"}
commons-io = {module = "commons-io:commons-io", version.ref = "commons-io"}
coroutines-android = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines"}
coroutines-core = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines"}
coroutines-test = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines-test"}
dexopener = {module = "com.github.tmurakami:dexopener", version.ref = "dexopener"}
facebook-screenshot = {module = "com.facebook.testing.screenshot:core", version.ref = "facebook-screenshot"}
flexmark-profile-pegdown = {module = "com.vladsch.flexmark:flexmark-profile-pegdown", version.ref = "flexmark-profile-pegdown"}
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}
json4s-jackson = {module = "org.json4s:json4s-jackson_2.13", version.ref = "json4s"}
json4s-native = {module = "org.json4s:json4s-native_2.13", version.ref = "json4s"}
junit = {module = "junit:junit", version.ref = "junit"}
keyboardvisibilityevent = {module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboardvisibilityevent"}
kodein = {module = "com.github.salomonbrys.kodein:kodein", version.ref = "kodein"}
kodein-android = {module = "com.github.salomonbrys.kodein:kodein-android", version.ref = "kodein"}
kodein-conf = {module = "com.github.salomonbrys.kodein:kodein-conf", version.ref = "kodein"}
kodein-core = {module = "com.github.salomonbrys.kodein:kodein-core", version.ref = "kodein"}
material = {module = "com.google.android.material:material", version.ref = "material"}
mockito-android = {module = "org.mockito:mockito-android", version.ref = "mockito-android"}
mockito-kotlin = {module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin"}
picasso = {module = "com.squareup.picasso:picasso", version.ref = "picasso"}
robolectric = {module = "org.robolectric:robolectric", version.ref = "robolectric"}
scala-library = {module = "org.scala-lang:scala-library", version.ref = "scala-library"}
scala-parallel = {module = "org.scala-lang.modules:scala-parallel-collections_2.13", version.ref = "scala-parallel"}
scala-xml = {module = "org.scala-lang.modules:scala-xml_2.13", version.ref = "scala-xml"}
scalamock = {module = "org.scalamock:scalamock_2.13", version.ref = "scalamock"}
scalatest = {module = "org.scalatest:scalatest_2.13", version.ref = "scalatest"}
scrimage-core = {module = "com.sksamuel.scrimage:scrimage-core", version.ref = "scrimage"}
scrimage-scala = {module = "com.sksamuel.scrimage:scrimage-scala_2.13", version.ref = "scrimage"}
skyiko-ktlint = {module = "com.github.shyiko:ktlint", version.ref = "skyiko-ktlint"}
tinyzip = {module = "io.github.bitstorm:tinyzip-core", version.ref = "tinyzip"}

android-apt-gradle-plugin = {module = "com.neenbedankt.gradle.plugins:android-apt", version = "1.8"}
android-gradle-plugin = {module = "com.android.tools.build:gradle", version.ref = "android-build-tools"}
composer-gradle-plugin = {module = "com.trevjonez.composer:plugin", version = "1.0.0-rc09"}
kotlin-gradle-plugin = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
ktlint-gradle-plugin = {module = "org.jlleitschuh.gradle:ktlint-gradle", version = "12.0.3"}
scalafmt-gradle-plugin = {module = "gradle.plugin.cz.alenkacz:gradle-scalafmt", version = "1.16.2"}
scalatest-gradle-plugin = {module = "gradle.plugin.com.github.maiflai:gradle-scalatest", version = "0.32"}
shot-gradle-plugin = { group = "com.github.nrotonda.shot", name = "shot", version.ref ="shot" }

[plugins]
vanniktech-publish-gradle-plugin = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }

[bundles]
androidx-test = ["androidx-espresso-core", "androidx-espresso-contrib", "androidx-espresso-intents", "androidx-test-core", "androidx-test-junit-ext", "androidx-test-rules", "androidx-test-runner"]
compose = ["androidx-compose-material", "androidx-compose-ui", "androidx-compose-ui-tooling"]
json4s = ["json4s-native", "json4s-jackson"]
kodein = ["kodein", "kodein-android", "kodein-conf", "kodein-core"]
scala = ["scala-library", "scala-parallel", "scala-xml"]
scala-test = ["scalamock", "scalatest"]
scrimage = ["scrimage-core", "scrimage-scala"]